apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: frontend-my-app-pro
  namespace: argocd
spec:
  description: Frontend project - Production
  sourceRepos:
    - https://github.com/aorko16/Helm-Argocd-multi-env-01.git
  destinations:
    - namespace: my-app-pro
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-pro
  namespace: argocd
spec:
  project: frontend-my-app-pro
  source:
    repoURL: https://github.com/aorko16/Helm-Argocd-multi-env-01.git
    targetRevision: main
    path: my-app
    helm:
      valueFiles:
        - values.yaml
        - values-pro.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app-pro
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
